spring:
  application:
    name: commerce-payment-system

  # AWS SSM Parameter Store에서 설정값을 주입받는 설정
  config:
    import: "aws-parameterstore:/cloud-project/prod/"

  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false # 운영에서도 성능을 위해 false 유지
    hibernate:
      ddl-auto: validate
    show-sql: false # 운영(prod) 환경에서는 로그가 너무 많이 쌓이므로 false로 설정

# 운영 서버에서 사용할 JWT 마스터키 (환경 변수)
jwt:
  secret: ${PROD_JWT_SECRET}
  expiration: 3600000 # 운영 환경 만료 시간

# 🚨 운영용 포트원 실결제 키 (환경 변수)
portone:
  base-url: "https://api.portone.io"
  api-secret: ${PROD_PORTONE_API_SECRET}
  store-id: ${PROD_PORTONE_STORE_ID}
  channel-key: ${PROD_PORTONE_CHANNEL_KEY}